name: Deploy on Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: bluebuilder/azure:5c26c4b
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login
        run: cd .azure && ./setup.sh --ci-login
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      # - name: Create infrastructure
      #   run: cd .azure && ./infra.sh update
      - name: Build project
        run: cd .azure && ./infra.sh env && ./build.sh
      - name: Deploy project
        run: cd .azure && ./deploy.sh
