name: Deploy to Azure
on:
  push:
    branches:
      - main

concurrency:
  group: deployment

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    container:
      image: cloudhue/azure:256a55b
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fix permissions
        run: chown -R $(id -u):$(id -g) .
      - name: Login
        run: .azure/setup.sh --ci-login
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Update infrastructure
        run: .azure/infra.sh update
      - name: Build project
        run: .azure/build.sh
      - name: Deploy project
        run: .azure/deploy.sh
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
