name: Trigger auto deployment for node-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/node-test-AutoDeployTrigger-6c7e66be-7879-4904-817b-458624ea036d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ylatest.azurecr.io
          username: ${{ secrets.NODETEST_REGISTRY_USERNAME }}
          password: ${{ secrets.NODETEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ylatest.azurecr.io/node-test:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NODETEST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n node-test -g _test --server ylatest.azurecr.io --username  ${{ secrets.NODETEST_REGISTRY_USERNAME }} --password ${{ secrets.NODETEST_REGISTRY_PASSWORD }}
            az containerapp update -n node-test -g _test --image ylatest.azurecr.io/node-test:${{ github.sha }}
